fastcampus-final/go-together-be

- src/main/java/com/example/gotogether/global/comfig/CustomAccessDeniedHandler.java
- src/main/java/com/example/gotogether/global/comfig/SecurityConfig.java
사용자 권한으로 관리자 요청시 403에러를 커스텀 에러로 변경
- SecurityConfig
> feat: accessDeniedHandler custom

- src/main/java/com/example/gotogether/admin/controller/AdminController.java
- src/main/java/com/example/gotogether/global/config/CustomAccessDeniedHandler.java
- src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
- src/main/java/com/example/gotogether/global/config/SecurityConfig.java
- src/main/java/com/example/gotogether/global/config/SwaggerConfig.java
Package ReName comfig -> config
> fix: Package ReName comfig -> config

- src/main/java/com/example/gotogether/auth/dto/UserDTO.java
> feat: SignupDTO add passwordConfirmation

- src/main/java/com/example/gotogether/auth/controller/AuthController.java
- src/main/java/com/example/gotogether/auth/service/Impl/UserServiceImpl.java
- src/main/java/com/example/gotogether/auth/service/UserService.java
이메일 중복 확인 API 추가
(프론트 엔드 요구사항)
- AuthController
- UserService
> Feat email duplication check

- src/main/resources/application.properties
> feat: server port 8080 -> 80

- src/main/java/com/example/gotogether/GotogetherApplication.java
- src/main/java/com/example/gotogether/auth/controller/AuthController.java
- src/main/java/com/example/gotogether/global/config/SecurityConfig.java
프론트 요청사항
이메일 사용가능 체크
+ timezone 셋팅
> Feat email check

- src/main/java/com/example/gotogether/auth/dto/UserDTO.java
> feat: 엔티티 수정

- .gitignore
- build.gradle
- src/main/java/com/example/gotogether/global/aws/AwsS3Controller.java
- src/main/java/com/example/gotogether/global/aws/AwsS3Service.java
AWS S3를 사용한 이미지 업로드 구현
#39  done
> Feat image

- src/main/java/com/example/gotogether/auth/controller/AuthController.java
- src/main/java/com/example/gotogether/auth/dto/MailDTO.java
- src/main/java/com/example/gotogether/auth/entity/User.java
- src/main/java/com/example/gotogether/auth/repository/UserRepository.java
- src/main/java/com/example/gotogether/auth/service/Impl/UserServiceImpl.java
- src/main/java/com/example/gotogether/auth/service/UserService.java
비밀번호를 까먹었을 경우 이메일 작성 시 
존재하는 이메일일 경우 메일 전송, 없는 경우 400에러
#30
> Feat: 임시 비밀번호 발급 구현

- build.gradle
- src/main/java/com/example/gotogether/auth/dto/UserDTO.java
- src/main/java/com/example/gotogether/auth/entity/User.java
- src/main/java/com/example/gotogether/auth/service/Impl/UserServiceImpl.java
1. 정보 중 비밀번호와 핸드폰 번호만 변경 가능
2. 회원정보 수정 시 사용되는 정보
전화번호, 기존 비밀번호, 변경할 비밀번호, 변경 될 비밀번호 2차확인
> feat: 회원 정보 수정 구현

- src/main/java/com/example/gotogether/category/controller/AdminCategoryController.java
- src/main/java/com/example/gotogether/category/controller/CategoryController.java
- src/main/java/com/example/gotogether/category/dto/CategoryDTO.java
- src/main/java/com/example/gotogether/category/entity/Category.java
- src/main/java/com/example/gotogether/category/repository/CategoryRepository.java
- src/main/java/com/example/gotogether/category/service/CategoryService.java
- src/main/java/com/example/gotogether/category/service/impl/CategoryServiceImpl.java
- src/main/java/com/example/gotogether/global/config/SecurityConfig.java
카테고리 CRUD 구현
무한 depth 를 이용하여 무한 카테고리 생성 가능
#38 done
> Feat categories

- src/main/java/com/example/gotogether/auth/service/Impl/UserServiceImpl.java
- src/main/java/com/example/gotogether/category/repository/CategoryRepository.java
- src/main/java/com/example/gotogether/product/controller/ProductController.java
- src/main/java/com/example/gotogether/product/controller/ProductOptionController.java
- src/main/java/com/example/gotogether/product/dto/ProductDTO.java
- src/main/java/com/example/gotogether/product/dto/ProductOptionDTO.java
- src/main/java/com/example/gotogether/product/entity/Product.java
- src/main/java/com/example/gotogether/product/entity/ProductCategory.java
- src/main/java/com/example/gotogether/product/entity/ProductOption.java
- src/main/java/com/example/gotogether/product/entity/ProductStatus.java
- src/main/java/com/example/gotogether/product/repository/ProductOptionRepository.java
- src/main/java/com/example/gotogether/product/repository/ProductRepository.java
- src/main/java/com/example/gotogether/product/service/Impl/ProductOptionServiceImpl.java
- src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
- src/main/java/com/example/gotogether/product/service/ProductOptionService.java
- src/main/java/com/example/gotogether/product/service/ProductService.java
> feat: 상품 추가 구현 (카테고리, 상품옵션 연동)

- src/main/java/com/example/gotogether/board/service/BoardService.java
- src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
> Feat: #35 Board 게시글 삭제 기능 구현

- src/main/java/com/example/gotogether/category/service/impl/CategoryServiceImpl.java
- src/main/java/com/example/gotogether/global/config/SecurityConfig.java
- src/main/java/com/example/gotogether/product/controller/ProductController.java
- src/main/java/com/example/gotogether/product/repository/ProductCategoryRepository.java
- src/main/java/com/example/gotogether/product/repository/ProductRepository.java
- src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
- src/main/java/com/example/gotogether/product/service/ProductService.java
간단한 검색 기능 구현 (정렬 X , 조건 X )
카테고리 삭제시 해당 카테고리를 포함하고 있는 상품에서 해당 카테고리 삭제
평일에 프론트 담당자 분과 얘기 후 조건 정렬 추후 구현
> feat: 검색 기능 임시 구현 (추후 refactoring 가능)

- src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
- src/main/java/com/example/gotogether/product/controller/AdminProductController.java
- src/main/java/com/example/gotogether/product/dto/ProductDTO.java
- src/main/java/com/example/gotogether/product/dto/ProductOptionDTO.java
- src/main/java/com/example/gotogether/product/entity/Product.java
- src/main/java/com/example/gotogether/product/entity/ProductOption.java
- src/main/java/com/example/gotogether/product/repository/ProductCategoryRepository.java
- src/main/java/com/example/gotogether/product/repository/ProductOptionRepository.java
- src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
- src/main/java/com/example/gotogether/product/service/ProductService.java
1. [ADMIN]상품 삭제(숨김) 기능
2. [ADMIN]상품 목록
3. 상품 상세 정보
4. 상품 정보 변경(카테고리O 옵션X)
#26
> feat: 상품관련 API 기능 구현

- src/main/java/com/example/gotogether/global/config/SecurityConfig.java
- src/main/java/com/example/gotogether/product/controller/AdminProductController.java
- src/main/java/com/example/gotogether/product/controller/AdminProductOptionController.java
- src/main/java/com/example/gotogether/product/controller/ProductController.java
- src/main/java/com/example/gotogether/product/dto/ProductDTO.java
- src/main/java/com/example/gotogether/product/dto/ProductOptionDTO.java
- src/main/java/com/example/gotogether/product/entity/ProductOption.java
- src/main/java/com/example/gotogether/product/repository/ProductOptionRepository.java
- src/main/java/com/example/gotogether/product/service/Impl/ProductOptionServiceImpl.java
- src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
- src/main/java/com/example/gotogether/product/service/ProductOptionService.java
> Feat 상품 옵션 CRUD 기능 구현

- build.gradle
- src/main/java/com/example/gotogether/auth/controller/AdminUserController.java
- src/main/java/com/example/gotogether/auth/controller/AuthController.java
- src/main/java/com/example/gotogether/auth/controller/UserController.java
- src/main/java/com/example/gotogether/board/controller/BoardController.java
- src/main/java/com/example/gotogether/category/controller/AdminCategoryController.java
- src/main/java/com/example/gotogether/category/controller/CategoryController.java
- src/main/java/com/example/gotogether/global/aws/AwsS3Controller.java
- src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
- src/main/java/com/example/gotogether/global/config/QuerydslConfiguration.java
- src/main/java/com/example/gotogether/global/config/SecurityConfig.java
- src/main/java/com/example/gotogether/page/controller/PageContentsAdminController.java
- src/main/java/com/example/gotogether/page/controller/PageContentsController.java
- src/main/java/com/example/gotogether/page/dto/RegionDTO.java
- src/main/java/com/example/gotogether/page/entity/Region.java
- src/main/java/com/example/gotogether/page/repository/RegionRepository.java
- src/main/java/com/example/gotogether/page/service/PageContentsService.java
- src/main/java/com/example/gotogether/page/service/impl/PageContentsServiceImpl.java
- src/main/java/com/example/gotogether/product/controller/ProductController.java
- src/main/java/com/example/gotogether/product/dto/ProductDTO.java
- src/main/java/com/example/gotogether/product/entity/Product.java
- src/main/java/com/example/gotogether/product/repository/ProductRepository.java
- src/main/java/com/example/gotogether/product/repository/ProductRepositoryCustom.java
- src/main/java/com/example/gotogether/product/repository/ProductRepositoryCustomImpl.java
- src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
- src/main/java/com/example/gotogether/product/service/ProductService.java
- src/main/java/com/example/gotogether/reservation/controller/AdminReservationController.java
3월28일 작업 내용
- queryDsl 도입
- queryDsl 사용한 검색 기능 ( 정렬 + 출발일 조건 + 인원수 조건 )
- queryDsl 사용한 인기 있는 상품 구현( with 카테고리 조건)
- 인기 지역 관리 시스템 구현 ( Create, Update, Delete)
- 인기 지역 리스트 조회 구현
- 전체적인 Swagger 가독성 증가
양이 조금 많습니다...
> Feat : querydsl and several API 

- src/main/java/com/example/gotogether/category/controller/CategoryController.java
- src/main/java/com/example/gotogether/category/service/CategoryService.java
- src/main/java/com/example/gotogether/category/service/impl/CategoryServiceImpl.java
- src/main/java/com/example/gotogether/global/config/SecurityConfig.java
- src/main/java/com/example/gotogether/page/controller/PageContentsAdminController.java
- src/main/java/com/example/gotogether/page/service/PageContentsService.java
- src/main/java/com/example/gotogether/page/service/impl/PageContentsServiceImpl.java
담당 기능 중 상세정보 조회  API 신규 추가
- 카테고리 상세 정보 조회
- 인기 지역 상세 정보 조회
> Feat details

- src/main/java/com/example/gotogether/product/controller/AdminProductController.java
- src/main/java/com/example/gotogether/product/controller/AdminProductOptionController.java
- src/main/java/com/example/gotogether/product/controller/ProductController.java
- src/main/java/com/example/gotogether/product/dto/ProductDTO.java
- src/main/java/com/example/gotogether/product/entity/Product.java
- src/main/java/com/example/gotogether/product/service/Impl/ProductOptionServiceImpl.java
- src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
- src/main/java/com/example/gotogether/product/service/ProductService.java
- 상품 추가와 수정 DTO가 같았던 것을 분리 했습니다.
- 예외처리 NoSuchElementException으로 변경
- 상태코드 설명 추가
> Refactoring Product

- src/main/java/com/example/gotogether/cart/controller/CartController.java
- src/main/java/com/example/gotogether/cart/dto/CartDTO.java
- src/main/java/com/example/gotogether/cart/entity/Cart.java
- src/main/java/com/example/gotogether/cart/repository/CartRepository.java
- src/main/java/com/example/gotogether/cart/service/CartService.java
- src/main/java/com/example/gotogether/cart/service/Impl/CartServiceImpl.java
- src/main/java/com/example/gotogether/product/controller/ProductController.java
- src/main/java/com/example/gotogether/product/entity/ProductOption.java
- src/main/java/com/example/gotogether/product/repository/ProductRepository.java
- src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
- src/main/java/com/example/gotogether/product/service/ProductService.java
- src/main/java/com/example/gotogether/wishlist/controller/WishlistController.java
- src/main/java/com/example/gotogether/wishlist/dto/WishlistDTO.java
- src/main/java/com/example/gotogether/wishlist/entity/Wishlist.java
- src/main/java/com/example/gotogether/wishlist/repository/WishlistRepository.java
- src/main/java/com/example/gotogether/wishlist/service/Impl/WishlistServiceImpl.java
- src/main/java/com/example/gotogether/wishlist/service/WishlistService.java
해당 상품과 같은 여행유형타입을 가진 상품의 리스트들을 가져온다.
> Feat: 관련상품 리스트

- src/main/java/com/example/gotogether/page/controller/PageContentsAdminController.java
- src/main/java/com/example/gotogether/page/controller/PageContentsController.java
- src/main/java/com/example/gotogether/page/dto/BannerDTO.java
- src/main/java/com/example/gotogether/page/entity/Banner.java
- src/main/java/com/example/gotogether/page/repository/BannerRepository.java
- src/main/java/com/example/gotogether/page/service/BannerService.java
- src/main/java/com/example/gotogether/page/service/impl/BannerServiceImpl.java
> Feat: Banner CRUD

- src/main/java/com/example/gotogether/board/controller/BoardController.java
- src/main/java/com/example/gotogether/board/dto/BoardDTO.java
- src/main/java/com/example/gotogether/board/entity/Board.java
- src/main/java/com/example/gotogether/board/service/BoardService.java
- src/main/java/com/example/gotogether/board/service/impl/BoardServiceImpl.java
> Feat: #78 Board 게시글 수정 기능 구현

- src/main/java/com/example/gotogether/auth/controller/AdminUserController.java
- src/main/java/com/example/gotogether/auth/controller/AuthController.java
- src/main/java/com/example/gotogether/auth/dto/UserDTO.java
- src/main/java/com/example/gotogether/auth/entity/User.java
- src/main/java/com/example/gotogether/product/controller/AdminProductController.java
- src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
User에 여권 영어 성, 영어 이름 추가
상품 조회시 데이터 없어도 상태코드 200으로 반환되던 현상 수정 -> 204로 반환
DB가 변경되어야 하기 때문에 변경하지 않고 사용하게 된다면 오류가 날 수 있습니다.
```
ALTER TABLE user MODIFY COLUMN passport_last_name VARCHAR(255) NOT NULL;
ALTER TABLE user MODIFY COLUMN passport_first_name VARCHAR(255) NOT NULL;
```
새로 DB를 만들어 사용하기 싫으신다면 위의 코드로 DB 변경하시면 됩니다.
> Feat: User 엔티티 수정

- src/main/java/com/example/gotogether/auth/controller/AdminUserController.java
- src/main/java/com/example/gotogether/auth/controller/UserController.java
- src/main/java/com/example/gotogether/auth/dto/GroupDTO.java
- src/main/java/com/example/gotogether/auth/dto/UserDTO.java
- src/main/java/com/example/gotogether/auth/entity/Grouping.java
- src/main/java/com/example/gotogether/auth/entity/User.java
- src/main/java/com/example/gotogether/auth/repository/GroupingRepository.java
- src/main/java/com/example/gotogether/auth/service/AdminService.java
- src/main/java/com/example/gotogether/auth/service/Impl/AdminServiceImpl.java
- src/main/java/com/example/gotogether/auth/service/Impl/UserServiceImpl.java
- src/main/java/com/example/gotogether/page/controller/PageContentsController.java
- src/main/java/com/example/gotogether/page/service/PageContentsService.java
- src/main/java/com/example/gotogether/page/service/impl/PageContentsServiceImpl.java
- src/main/java/com/example/gotogether/product/repository/ProductCategoryRepository.java
- src/main/java/com/example/gotogether/product/repository/ProductRepository.java
- src/main/java/com/example/gotogether/product/repository/ProductRepositoryCustom.java
- src/main/java/com/example/gotogether/product/repository/ProductRepositoryCustomImpl.java
- src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
그룹화 테이블 및 유저 엔티티 변경.
유저 엔티티가 변경되었고, 사실 상품 테이블까지 건들고 싶었지만 일이 너무 커지기에 감당 못할것같아 String으로 대체하였습니다.
조금 판단이 흐려진것같아 정밀한 코드리뷰가 필요합니다.
유저 엔티티 수정으로 인해 기존 DB 드랍 후 create 를 고려중입니다.
해당 구조로 그룹 상품 추천 구현하였습니다.
> Feat grouping

- src/main/java/com/example/gotogether/auth/dto/UserDTO.java
- src/main/java/com/example/gotogether/auth/service/Impl/UserServiceImpl.java
- src/main/java/com/example/gotogether/cart/service/Impl/CartServiceImpl.java
- src/main/java/com/example/gotogether/product/repository/ProductRepository.java
- src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
수정사항
- 회원정보요청시 패스워드 빼고 전부 반환되도록해야합니다. #31 
- 장바구니  content갯수 0개 일때 예외처리 #27 
- 카테고리 상품 검색에서 content갯수 0개 일때 예외처리 #38 
- FE요구사항- 관리자 계정 회원 리스트 조회 시 관리자 여부 추가 #31 
- UserDTO 코드 리팩토링
> Feat: 수정사항(User, Cart, Product)

- src/main/java/com/example/gotogether/product/repository/ProductRepository.java
> develop branch 최신화

- src/main/java/com/example/gotogether/auth/controller/AdminUserController.java
- src/main/java/com/example/gotogether/auth/service/Impl/UserServiceImpl.java
- src/main/java/com/example/gotogether/cart/controller/CartController.java
- src/main/java/com/example/gotogether/cart/service/Impl/CartServiceImpl.java
- src/main/java/com/example/gotogether/product/controller/AdminProductController.java
- src/main/java/com/example/gotogether/product/controller/ProductController.java
- src/main/java/com/example/gotogether/wishlist/controller/WishlistController.java
- 상세 정보 url 중 detail이 아니던 url 수정(f1e08885928038f1d3d719eecaf2b36890dee0e0),(3f640f812f787fc95beccbdc55c57f158e294014), (9e5ebda2b4d2855e78b5b530dbdc2b0fee22f628)
- 그 외 자잘한 오류 수정 (02e1d62c50b9ef7df3d92a7443583c66ebb8c255), (4cff56dd55c6e17396c83267322b1f0099fe8898)
- UserServicImpl (https://github.com/fastcampus-final/go-together-be/commit/82f527aff53a148beff22f243e1941839b187159)
1. [여권 이름과 성이 둘중 하나에서 둘다 대문자만 사용 가능하도록 수정]
- CartServiceImpl (https://github.com/fastcampus-final/go-together-be/commit/912ae3958cc2ab4c028781d5022393b3b114f0bc)
1. 최대 싱글룸 수에서 현재 인원수를 빼던 오류 수정
2. Swagger에서 responsebody에 한글이 출력이 안되기 때문에 오류 설명을 영어로 출력
> Refactor: URL ect

- src/main/java/com/example/gotogether/auth/dto/UserDTO.java
- src/main/java/com/example/gotogether/auth/service/Impl/AdminServiceImpl.java
- src/main/java/com/example/gotogether/product/dto/ProductDTO.java
- src/main/java/com/example/gotogether/product/dto/ProductOptionDTO.java
- src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
230404 프런트 요청 사항 반영 #109 
- 사용자 정보 수정 by admin 을 수정 할 부분만 수정 가능하게 변경.
- 사용자의 type이 null일시 발생하는 nullpointerexception 방지
- 상품 생성시 그룹이 없어도 생성되도록 변경
- 상품 상세정보 출력시 날짜 포맷 변경
> feat - 프런트 요청 사항 반영

- src/main/java/com/example/gotogether/auth/service/Impl/UserServiceImpl.java
> fix: 비밀번호 패턴 삭제

- src/main/java/com/example/gotogether/cart/controller/CartController.java
- src/main/java/com/example/gotogether/global/config/SecurityConfig.java
- src/main/java/com/example/gotogether/page/controller/PageContentsAdminController.java
- src/main/java/com/example/gotogether/wishlist/controller/WishlistController.java
- [Refactor: URL 수정, SecurityConfig추가](https://github.com/fastcampus-final/go-together-be/commit/d836709683f3016827bfc18932cf5f7b242be338)
> Refactor: URL 코드 수정

- src/main/java/com/example/gotogether/product/dto/ProductOptionDTO.java
상품 옵션 추가 시 현재 인원, 싱글룸 수 추가시키지 못하게 변경
> feat: 상품 옵션 

- src/main/java/com/example/gotogether/page/controller/PageContentsController.java
> feat: 배너리스트

- src/main/java/com/example/gotogether/global/config/PageSizeConfig.java
- src/main/java/com/example/gotogether/wishlist/dto/WishlistDTO.java
프론트 요청사항 반영.
- productThubnail 오타
- 키워드 / 카테고리로 상품 검색 시 size 를 12개씩
> Feat 0409 front

- src/main/java/com/example/gotogether/wishlist/controller/WishlistController.java
- src/main/java/com/example/gotogether/wishlist/service/Impl/WishlistServiceImpl.java
위시 리스트 사이즈가 0일때 빈배열이 응답되는 현상 수정
> fix: 위시리스트 예외처리 변경

- src/main/java/com/example/gotogether/wishlist/controller/WishlistController.java
- src/main/java/com/example/gotogether/wishlist/service/Impl/WishlistServiceImpl.java
- src/main/java/com/example/gotogether/wishlist/service/WishlistService.java
위시리스트 삭제 wishlistId를 @PathVariable로 받음
> fix: 위시리스트 삭제 수정

- src/main/java/com/example/gotogether/cart/dto/CartDTO.java
- src/main/java/com/example/gotogether/cart/service/Impl/CartServiceImpl.java
- src/main/java/com/example/gotogether/product/dto/ProductOptionDTO.java
> Feat 0410 cart

- src/main/java/com/example/gotogether/product/service/Impl/ProductOptionServiceImpl.java
- src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
- src/main/java/com/example/gotogether/wishlist/dto/WishlistDTO.java
> fix: 상품옵션 예외처리 추가

- src/main/java/com/example/gotogether/cart/dto/CartDTO.java
> feat: 장바구니 출력값 변경

- src/main/java/com/example/gotogether/page/dto/BannerDTO.java
- src/main/java/com/example/gotogether/page/entity/Banner.java
배너 출력 방식 변경.
- banner DTO
- banner Entity
> Feat banner

- src/main/java/com/example/gotogether/product/service/Impl/ProductServiceImpl.java
상품수정시, group이 없는 경우에도 작동되도록 수정
> feat: 상품수정시, group이 없는 경우에도 작동되도록 수정
